version: '3.8'

services:
  db:
    image: postgres:14.7
    restart: always
    ports:
      - 5432:5432
    networks:
      - app-net
    environment:
      - name=value
  api-client:
    

networks:
  app-net:
    external: true
