// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: newsjobs.sql

package model

import (
	"context"
)

const createNewsJob = `-- name: CreateNewsJob :one
INSERT INTO newsjobs (
    job_id, news_id
) VALUES (
    $1, $2
)
RETURNING id
`

type CreateNewsJobParams struct {
	JobID  int64 `json:"job_id"`
	NewsID int64 `json:"news_id"`
}

func (q *Queries) CreateNewsJob(ctx context.Context, arg *CreateNewsJobParams) (int64, error) {
	row := q.db.QueryRow(ctx, createNewsJob, arg.JobID, arg.NewsID)
	var id int64
	err := row.Scan(&id)
	return id, err
}
