// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package models

import (
	"context"
)

type Querier interface {
	CreateAPI(ctx context.Context, arg *CreateAPIParams) error
	CreateAPIKey(ctx context.Context, arg *CreateAPIKeyParams) error
	CreateUser(ctx context.Context, arg *CreateUserParams) error
	DeleteAPI(ctx context.Context, id int16) error
	DeleteAPIKey(ctx context.Context, arg *DeleteAPIKeyParams) error
	DeleteUser(ctx context.Context, id int32) error
	GetAPI(ctx context.Context, id int16) (*GetAPIRow, error)
	GetAPIKey(ctx context.Context, arg *GetAPIKeyParams) (*GetAPIKeyRow, error)
	GetUserAuth(ctx context.Context, email string) (*GetUserAuthRow, error)
	HardAPIKey(ctx context.Context, arg *HardAPIKeyParams) error
	HardDeleteAPI(ctx context.Context, id int16) error
	HardDeleteUser(ctx context.Context, id int32) error
	UpdateAPI(ctx context.Context, arg *UpdateAPIParams) error
	UpdateAPIKey(ctx context.Context, arg *UpdateAPIKeyParams) error
	UpdatePassword(ctx context.Context, arg *UpdatePasswordParams) error
}

var _ Querier = (*Queries)(nil)
