// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package model

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CleanUpAPIKey(ctx context.Context) (int64, error)
	CleanUpAPIs(ctx context.Context) (int64, error)
	CleanUpJobs(ctx context.Context) (int64, error)
	CleanUpUsers(ctx context.Context) (int64, error)
	CountEndpoint(ctx context.Context) (int64, error)
	CountJob(ctx context.Context, owner uuid.UUID) ([]*CountJobRow, error)
	CreateAPI(ctx context.Context, arg *CreateAPIParams) (int16, error)
	CreateAPIKey(ctx context.Context, arg *CreateAPIKeyParams) (int32, error)
	CreateEndpoint(ctx context.Context, arg *CreateEndpointParams) (int32, error)
	CreateJob(ctx context.Context, arg *CreateJobParams) (int32, error)
	CreateKeyword(ctx context.Context, arg *CreateKeywordParams) (int64, error)
	CreateLog(ctx context.Context, arg *CreateLogParams) (int64, error)
	CreateNews(ctx context.Context, arg *CreateNewsParams) (int64, error)
	CreateNewsJob(ctx context.Context, arg *CreateNewsJobParams) (int64, error)
	CreateUser(ctx context.Context, arg *CreateUserParams) (uuid.UUID, error)
	DeleteAPI(ctx context.Context, id int16) (int64, error)
	DeleteAPIKey(ctx context.Context, arg *DeleteAPIKeyParams) (int64, error)
	DeleteEndpoint(ctx context.Context, id int32) (int64, error)
	DeleteJob(ctx context.Context, arg *DeleteJobParams) (int64, error)
	DeleteKeyword(ctx context.Context, keyword string) (int64, error)
	DeleteNews(ctx context.Context, id int64) (int64, error)
	DeleteNewsPublishBefore(ctx context.Context, beforeTime pgtype.Timestamptz) (int64, error)
	DeleteUser(ctx context.Context, id uuid.UUID) (int64, error)
	GetAPI(ctx context.Context, id int16) (*Api, error)
	GetAPIKey(ctx context.Context, arg *GetAPIKeyParams) (*GetAPIKeyRow, error)
	GetContentById(ctx context.Context, ids []int32) ([]*GetContentByIdRow, error)
	GetJobByOwnerFilterByJIdAndStatus(ctx context.Context, arg *GetJobByOwnerFilterByJIdAndStatusParams) ([]*GetJobByOwnerFilterByJIdAndStatusRow, error)
	GetJobByOwnerFilterByJIdRange(ctx context.Context, arg *GetJobByOwnerFilterByJIdRangeParams) ([]*GetJobByOwnerFilterByJIdRangeRow, error)
	GetJobByOwnerFilterByJIds(ctx context.Context, arg *GetJobByOwnerFilterByJIdsParams) ([]*GetJobByOwnerFilterByJIdsRow, error)
	GetJobsByJobId(ctx context.Context, arg *GetJobsByJobIdParams) (*GetJobsByJobIdRow, error)
	GetJobsByOwner(ctx context.Context, arg *GetJobsByOwnerParams) ([]*GetJobsByOwnerRow, error)
	GetJobsByOwnerFilterByStatus(ctx context.Context, arg *GetJobsByOwnerFilterByStatusParams) ([]*GetJobsByOwnerFilterByStatusRow, error)
	GetKeywordsByNewsId(ctx context.Context, newsID []int32) ([]string, error)
	GetLastJobId(ctx context.Context, owner uuid.UUID) ([]*GetLastJobIdRow, error)
	GetLogByUserId(ctx context.Context, arg *GetLogByUserIdParams) ([]*Log, error)
	GetLogByUserIdNext(ctx context.Context, arg *GetLogByUserIdNextParams) ([]*Log, error)
	GetNewsByJob(ctx context.Context) ([]*GetNewsByJobRow, error)
	GetNewsByKeywords(ctx context.Context, keywords []string) ([]*GetNewsByKeywordsRow, error)
	GetNewsByMD5Hash(ctx context.Context, md5Hash string) (*GetNewsByMD5HashRow, error)
	GetNewsByMD5Hashs(ctx context.Context, md5Hash []string) ([]int64, error)
	GetNewsPublishBetween(ctx context.Context, arg *GetNewsPublishBetweenParams) ([]*GetNewsPublishBetweenRow, error)
	GetUserAuth(ctx context.Context, email string) (*GetUserAuthRow, error)
	HardDeleteUser(ctx context.Context, id uuid.UUID) (int64, error)
	ListAPI(ctx context.Context, n int32) ([]*ListAPIRow, error)
	ListAPIByType(ctx context.Context, apitype ApiType) ([]*ListAPIByTypeRow, error)
	ListAPIKey(ctx context.Context, owner uuid.UUID) ([]*ListAPIKeyRow, error)
	ListAllEndpoint(ctx context.Context, arg *ListAllEndpointParams) ([]*ListAllEndpointRow, error)
	ListEndpointByOwner(ctx context.Context, owner uuid.UUID) ([]*ListEndpointByOwnerRow, error)
	ListRecentNNews(ctx context.Context, n int32) ([]*ListRecentNNewsRow, error)
	UpdateAPI(ctx context.Context, arg *UpdateAPIParams) (int64, error)
	UpdateAPIKey(ctx context.Context, arg *UpdateAPIKeyParams) (int64, error)
	UpdateJobStatus(ctx context.Context, arg *UpdateJobStatusParams) (int64, error)
	UpdatePassword(ctx context.Context, arg *UpdatePasswordParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
