// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0
// source: proto/news_parser/news_parser.proto

package newsParser

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParseURLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	URL string `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL,omitempty"`
}

func (x *ParseURLRequest) Reset() {
	*x = ParseURLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_news_parser_news_parser_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParseURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseURLRequest) ProtoMessage() {}

func (x *ParseURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_news_parser_news_parser_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseURLRequest.ProtoReflect.Descriptor instead.
func (*ParseURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_news_parser_news_parser_proto_rawDescGZIP(), []int{0}
}

func (x *ParseURLRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ParseURLRequest) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

type ParseURLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64     `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	NewsItem *NewsItem `protobuf:"bytes,2,opt,name=NewsItem,proto3,oneof" json:"NewsItem,omitempty"`
	Error    *Error    `protobuf:"bytes,3,opt,name=Error,proto3,oneof" json:"Error,omitempty"`
}

func (x *ParseURLResponse) Reset() {
	*x = ParseURLResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_news_parser_news_parser_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParseURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseURLResponse) ProtoMessage() {}

func (x *ParseURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_news_parser_news_parser_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseURLResponse.ProtoReflect.Descriptor instead.
func (*ParseURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_news_parser_news_parser_proto_rawDescGZIP(), []int{1}
}

func (x *ParseURLResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ParseURLResponse) GetNewsItem() *NewsItem {
	if x != nil {
		return x.NewsItem
	}
	return nil
}

func (x *ParseURLResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type NewsItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string                 `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Link        string                 `protobuf:"bytes,2,opt,name=Link,proto3" json:"Link,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Language    string                 `protobuf:"bytes,4,opt,name=Language,proto3" json:"Language,omitempty"`
	Author      []string               `protobuf:"bytes,5,rep,name=Author,proto3" json:"Author,omitempty"`
	Category    string                 `protobuf:"bytes,6,opt,name=Category,proto3" json:"Category,omitempty"`
	GUID        string                 `protobuf:"bytes,7,opt,name=GUID,proto3" json:"GUID,omitempty"`
	PubDate     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=PubDate,proto3" json:"PubDate,omitempty"`
	Content     []string               `protobuf:"bytes,9,rep,name=Content,proto3" json:"Content,omitempty"`
	Tag         []string               `protobuf:"bytes,10,rep,name=Tag,proto3" json:"Tag,omitempty"`
	RelatedGUID []string               `protobuf:"bytes,11,rep,name=RelatedGUID,proto3" json:"RelatedGUID,omitempty"`
}

func (x *NewsItem) Reset() {
	*x = NewsItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_news_parser_news_parser_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsItem) ProtoMessage() {}

func (x *NewsItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_news_parser_news_parser_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsItem.ProtoReflect.Descriptor instead.
func (*NewsItem) Descriptor() ([]byte, []int) {
	return file_proto_news_parser_news_parser_proto_rawDescGZIP(), []int{2}
}

func (x *NewsItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NewsItem) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *NewsItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *NewsItem) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *NewsItem) GetAuthor() []string {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *NewsItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *NewsItem) GetGUID() string {
	if x != nil {
		return x.GUID
	}
	return ""
}

func (x *NewsItem) GetPubDate() *timestamppb.Timestamp {
	if x != nil {
		return x.PubDate
	}
	return nil
}

func (x *NewsItem) GetContent() []string {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *NewsItem) GetTag() []string {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *NewsItem) GetRelatedGUID() []string {
	if x != nil {
		return x.RelatedGUID
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Details []string `protobuf:"bytes,3,rep,name=Details,proto3" json:"Details,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_news_parser_news_parser_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_news_parser_news_parser_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_news_parser_news_parser_proto_rawDescGZIP(), []int{3}
}

func (x *Error) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDetails() []string {
	if x != nil {
		return x.Details
	}
	return nil
}

type GetGUIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	URL string `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL,omitempty"`
}

func (x *GetGUIDRequest) Reset() {
	*x = GetGUIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_news_parser_news_parser_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGUIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGUIDRequest) ProtoMessage() {}

func (x *GetGUIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_news_parser_news_parser_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGUIDRequest.ProtoReflect.Descriptor instead.
func (*GetGUIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_news_parser_news_parser_proto_rawDescGZIP(), []int{4}
}

func (x *GetGUIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetGUIDRequest) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

type GetGUIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	GUID string `protobuf:"bytes,2,opt,name=GUID,proto3" json:"GUID,omitempty"`
}

func (x *GetGUIDResponse) Reset() {
	*x = GetGUIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_news_parser_news_parser_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGUIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGUIDResponse) ProtoMessage() {}

func (x *GetGUIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_news_parser_news_parser_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGUIDResponse.ProtoReflect.Descriptor instead.
func (*GetGUIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_news_parser_news_parser_proto_rawDescGZIP(), []int{5}
}

func (x *GetGUIDResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetGUIDResponse) GetGUID() string {
	if x != nil {
		return x.GUID
	}
	return ""
}

type PingPong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signal bool `protobuf:"varint,1,opt,name=signal,proto3" json:"signal,omitempty"`
}

func (x *PingPong) Reset() {
	*x = PingPong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_news_parser_news_parser_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingPong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingPong) ProtoMessage() {}

func (x *PingPong) ProtoReflect() protoreflect.Message {
	mi := &file_proto_news_parser_news_parser_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingPong.ProtoReflect.Descriptor instead.
func (*PingPong) Descriptor() ([]byte, []int) {
	return file_proto_news_parser_news_parser_proto_rawDescGZIP(), []int{6}
}

func (x *PingPong) GetSignal() bool {
	if x != nil {
		return x.Signal
	}
	return false
}

var File_proto_news_parser_news_parser_proto protoreflect.FileDescriptor

var file_proto_news_parser_news_parser_proto_rawDesc = []byte{
	0x0a, 0x23, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x65, 0x77, 0x73, 0x5f, 0x70, 0x61, 0x72,
	0x73, 0x65, 0x72, 0x2f, 0x6e, 0x65, 0x77, 0x73, 0x5f, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6e, 0x65, 0x77, 0x73, 0x50, 0x61, 0x72, 0x73, 0x65,
	0x72, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x33, 0x0a, 0x0f, 0x50, 0x61, 0x72, 0x73, 0x65, 0x55, 0x52, 0x4c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x52, 0x4c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x55, 0x52, 0x4c, 0x22, 0x9e, 0x01, 0x0a, 0x10, 0x50, 0x61, 0x72, 0x73,
	0x65, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x35, 0x0a, 0x08,
	0x4e, 0x65, 0x77, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x6e, 0x65, 0x77, 0x73, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x2e, 0x4e, 0x65, 0x77, 0x73,
	0x49, 0x74, 0x65, 0x6d, 0x48, 0x00, 0x52, 0x08, 0x4e, 0x65, 0x77, 0x73, 0x49, 0x74, 0x65, 0x6d,
	0x88, 0x01, 0x01, 0x12, 0x2c, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6e, 0x65, 0x77, 0x73, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x01, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01,
	0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x4e, 0x65, 0x77, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x42, 0x08,
	0x0a, 0x06, 0x5f, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xbe, 0x02, 0x0a, 0x08, 0x4e, 0x65, 0x77,
	0x73, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4c,
	0x69, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4c, 0x69, 0x6e, 0x6b, 0x12,
	0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x41,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x47, 0x55, 0x49, 0x44, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x47, 0x55, 0x49, 0x44, 0x12, 0x34, 0x0a, 0x07, 0x50, 0x75, 0x62, 0x44, 0x61, 0x74, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x07, 0x50, 0x75, 0x62, 0x44, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x09, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x18, 0x0a, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x03, 0x54, 0x61, 0x67, 0x12, 0x20, 0x0a, 0x0b, 0x52, 0x65, 0x6c, 0x61, 0x74,
	0x65, 0x64, 0x47, 0x55, 0x49, 0x44, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x52, 0x65,
	0x6c, 0x61, 0x74, 0x65, 0x64, 0x47, 0x55, 0x49, 0x44, 0x22, 0x4f, 0x0a, 0x05, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x07, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x32, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x47, 0x55, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x55, 0x52, 0x4c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x52, 0x4c, 0x22, 0x35,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x47, 0x55, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x47, 0x55, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x47, 0x55, 0x49, 0x44, 0x22, 0x22, 0x0a, 0x08, 0x50, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6e,
	0x67, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x32, 0xd1, 0x01, 0x0a, 0x09, 0x55, 0x52,
	0x4c, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x12, 0x39, 0x0a, 0x0b, 0x48, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x14, 0x2e, 0x6e, 0x65, 0x77, 0x73, 0x50, 0x61, 0x72,
	0x73, 0x65, 0x72, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6e, 0x67, 0x1a, 0x14, 0x2e, 0x6e,
	0x65, 0x77, 0x73, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x50, 0x6f,
	0x6e, 0x67, 0x12, 0x45, 0x0a, 0x08, 0x50, 0x61, 0x72, 0x73, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x1b,
	0x2e, 0x6e, 0x65, 0x77, 0x73, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x72, 0x73,
	0x65, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6e, 0x65,
	0x77, 0x73, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x55, 0x52,
	0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x07, 0x47, 0x65, 0x74,
	0x47, 0x55, 0x49, 0x44, 0x12, 0x1a, 0x2e, 0x6e, 0x65, 0x77, 0x73, 0x50, 0x61, 0x72, 0x73, 0x65,
	0x72, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x55, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1b, 0x2e, 0x6e, 0x65, 0x77, 0x73, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x2e, 0x47, 0x65,
	0x74, 0x47, 0x55, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x35, 0x5a,
	0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x43, 0x68, 0x69, 0x61,
	0x59, 0x75, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x65,
	0x77, 0x73, 0x5f, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72, 0x2f, 0x6e, 0x65, 0x77, 0x73, 0x50, 0x61,
	0x72, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_news_parser_news_parser_proto_rawDescOnce sync.Once
	file_proto_news_parser_news_parser_proto_rawDescData = file_proto_news_parser_news_parser_proto_rawDesc
)

func file_proto_news_parser_news_parser_proto_rawDescGZIP() []byte {
	file_proto_news_parser_news_parser_proto_rawDescOnce.Do(func() {
		file_proto_news_parser_news_parser_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_news_parser_news_parser_proto_rawDescData)
	})
	return file_proto_news_parser_news_parser_proto_rawDescData
}

var file_proto_news_parser_news_parser_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_news_parser_news_parser_proto_goTypes = []interface{}{
	(*ParseURLRequest)(nil),       // 0: newsParser.ParseURLRequest
	(*ParseURLResponse)(nil),      // 1: newsParser.ParseURLResponse
	(*NewsItem)(nil),              // 2: newsParser.NewsItem
	(*Error)(nil),                 // 3: newsParser.Error
	(*GetGUIDRequest)(nil),        // 4: newsParser.GetGUIDRequest
	(*GetGUIDResponse)(nil),       // 5: newsParser.GetGUIDResponse
	(*PingPong)(nil),              // 6: newsParser.PingPong
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_proto_news_parser_news_parser_proto_depIdxs = []int32{
	2, // 0: newsParser.ParseURLResponse.NewsItem:type_name -> newsParser.NewsItem
	3, // 1: newsParser.ParseURLResponse.Error:type_name -> newsParser.Error
	7, // 2: newsParser.NewsItem.PubDate:type_name -> google.protobuf.Timestamp
	6, // 3: newsParser.URLParser.HealthCheck:input_type -> newsParser.PingPong
	0, // 4: newsParser.URLParser.ParseUrl:input_type -> newsParser.ParseURLRequest
	4, // 5: newsParser.URLParser.GetGUID:input_type -> newsParser.GetGUIDRequest
	6, // 6: newsParser.URLParser.HealthCheck:output_type -> newsParser.PingPong
	1, // 7: newsParser.URLParser.ParseUrl:output_type -> newsParser.ParseURLResponse
	5, // 8: newsParser.URLParser.GetGUID:output_type -> newsParser.GetGUIDResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_news_parser_news_parser_proto_init() }
func file_proto_news_parser_news_parser_proto_init() {
	if File_proto_news_parser_news_parser_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_news_parser_news_parser_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParseURLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_news_parser_news_parser_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParseURLResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_news_parser_news_parser_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewsItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_news_parser_news_parser_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_news_parser_news_parser_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGUIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_news_parser_news_parser_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGUIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_news_parser_news_parser_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingPong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_news_parser_news_parser_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_news_parser_news_parser_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_news_parser_news_parser_proto_goTypes,
		DependencyIndexes: file_proto_news_parser_news_parser_proto_depIdxs,
		MessageInfos:      file_proto_news_parser_news_parser_proto_msgTypes,
	}.Build()
	File_proto_news_parser_news_parser_proto = out.File
	file_proto_news_parser_news_parser_proto_rawDesc = nil
	file_proto_news_parser_news_parser_proto_goTypes = nil
	file_proto_news_parser_news_parser_proto_depIdxs = nil
}
