NewSourceAPI:
  - NewsAPI:
    Name: NewsAPI
    Logo: NEWS_API_logo.png
    Endpoint:
      - Everything:
        Name: everything
        Parameters:
          text:
            - keywords
            - sources
            - domains
            - excluded-domains
            - language
            - sort-by
          time:
            - from
            - to
          select:
            - SearchIn:
                - title
                - description
                - content
      - Top-headlines
      - Sources
    DocumentUrl: https://newsapi.org/docs/endpoints
  - NEWSDATA.IO:
    Name: NEWSDATA.IO
    Logo: NEWSDATA.IO_logo.png
    Endpoint:
      - News
      - Archive
      - Sources
    DocumentUrl: https://newsdata.io/documentation/
  - GNews:
    Name: GNews
    Logo: GNews_logo.png
    Endpoint:
      - Search
      - Top-headlines
ModelAPI:
  - OpenAI:
    Name: OpenAI
    Logo: OpenAI_logo.svg
