development:
  dialect: { { envOr "DB_DIALECT" "postgres" } }
  database: { { envOr "DB_NAME" "news_dev" } }
  host: { { envOr "DB_HOST" "127.0.0.1" } }
  port: { { envOr "DB_PORT" "5432" } }
  user: { { envOr "DB_USER" "postgres" } }
  password: { { envOr "DB_PASSWORD" "postgres" } }

production:
  dialect: { { envOr "DB_DIALECT" "postgres" } }
  database: { { envOr "DB_NAME" "news" } }
  host: { { envOr "DB_HOST" "127.0.0.1" } }
  port: { { envOr "DB_PORT" "5432" } }
  user: { { envOr "DB_USER" "postgres" } }
  password: { { envOr "DB_PASSWORD" "postgres" } }
