version: 2
sql:
  - schema: ../db/schema.sql
    queries: ../db/query
    engine: postgresql
    gen:
      go:
        package: model
        out: ../internal/model
        sql_package: pgx/v5
        emit_prepared_queries: true
        emit_interface: true
        emit_json_tags: true
        emit_result_struct_pointers: true
        emit_params_struct_pointers: true
        json_tags_case_style: none
        output_db_file_name: db.go
        output_models_file_name: model.go
        output_querier_file_name: querier.go
        overrides:
          - db_type: "uuid"
            go_type: "github.com/google/uuid.UUID"
          - db_type: "uuid"
            go_type: "github.com/google/uuid.UUID"
            nullable: true
