package newsdata

import "github.com/ChiaYuChang/NewsSentimentAnalyzer/internal/server/validator"

var Category = map[string]string{
	Business:      "Business",
	Entertainment: "Entertainment",
	Environment:   "Environment",
	Food:          "Food",
	Health:        "Health",
	Politics:      "Politics",
	Science:       "Science",
	Sports:        "Sports",
	Technology:    "Technology",
	Top:           "Top",
	Tourism:       "Tourism",
	World:         "World",
}

var CategoryValidator = validator.NewEnmusFromMap(
	VAL_TAG_CATEGORY, Category, "key",
)

var Country = map[string]string{
	Afghanistan:          "Afghanistan",
	Albania:              "Albania",
	Algeria:              "Algeria",
	Angola:               "Angola",
	Argentina:            "Argentina",
	Australia:            "Australia",
	Austria:              "Austria",
	Azerbaijan:           "Azerbaijan",
	Bahrain:              "Bahrain",
	Bangladesh:           "Bangladesh",
	Barbados:             "Barbados",
	Belarus:              "Belarus",
	Belgium:              "Belgium",
	Bermuda:              "Bermuda",
	Bhutan:               "Bhutan",
	Bolivia:              "Bolivia",
	BosniaAndHerzegovina: "Bosnia And Herzegovina",
	Brazil:               "Brazil",
	Brunei:               "Brunei",
	Bulgaria:             "Bulgaria",
	Burkinafasco:         "Burkinafasco",
	Cambodia:             "Cambodia",
	Cameroon:             "Cameroon",
	Canada:               "Canada",
	CapeVerde:            "CapeVerde",
	CaymanIslands:        "Cayman Islands",
	Chile:                "Chile",
	China:                "China",
	Colombia:             "Colombia",
	Comoros:              "Comoros",
	CostaRica:            "Costa Rica",
	CotedIvoire:          "Côte d'Ivoire",
	Croatia:              "Croatia",
	Cuba:                 "Cuba",
	Cyprus:               "Cyprus",
	CzechRepublic:        "Czech Republic",
	Denmark:              "Denmark",
	Djibouti:             "Djibouti",
	Dominica:             "Dominica",
	DominicanRepublic:    "Dominican Republic",
	DRCongo:              "Democratic Republic of the Congo",
	Ecuador:              "Ecuador",
	Egypt:                "Egypt",
	ElSalvador:           "ElSalvador",
	Estonia:              "Estonia",
	Ethiopia:             "Ethiopia",
	Fiji:                 "Fiji",
	Finland:              "Finland",
	France:               "France",
	FrenchPolynesia:      "French Polynesia",
	Gabon:                "Gabon",
	Georgia:              "Georgia",
	Germany:              "Germany",
	Ghana:                "Ghana",
	Greece:               "Greece",
	Guatemala:            "Guatemala",
	Guinea:               "Guinea",
	Haiti:                "Haiti",
	Honduras:             "Honduras",
	HongKong:             "Hong Kong",
	Hungary:              "Hungary",
	Iceland:              "Iceland",
	India:                "India",
	Indonesia:            "Indonesia",
	Iraq:                 "Iraq",
	Ireland:              "Ireland",
	Israel:               "Israel",
	Italy:                "Italy",
	Jamaica:              "Jamaica",
	Japan:                "Japan",
	Jordan:               "Jordan",
	Kazakhstan:           "Kazakhstan",
	Kenya:                "Kenya",
	Kuwait:               "Kuwait",
	Kyrgyzstan:           "Kyrgyzstan",
	Latvia:               "Latvia",
	Lebanon:              "Lebanon",
	Libya:                "Libya",
	Lithuania:            "Lithuania",
	Luxembourg:           "Luxembourg",
	Macau:                "Macau",
	Macedonia:            "Macedonia",
	Madagascar:           "Madagascar",
	Malawi:               "Malawi",
	Malaysia:             "Malaysia",
	Maldives:             "Maldives",
	Mali:                 "Mali",
	Malta:                "Malta",
	Mauritania:           "Mauritania",
	Mexico:               "Mexico",
	Moldova:              "Moldova",
	Mongolia:             "Mongolia",
	Montenegro:           "Montenegro",
	Morocco:              "Morocco",
	Mozambique:           "Mozambique",
	Myanmar:              "Myanmar",
	Namibia:              "Namibia",
	Nepal:                "Nepal",
	Netherland:           "Netherland",
	Newzealand:           "New Zealand",
	Niger:                "Niger",
	Nigeria:              "Nigeria",
	Northkorea:           "North Korea",
	Norway:               "Norway",
	Oman:                 "Oman",
	Pakistan:             "Pakistan",
	Panama:               "Panama",
	Paraguay:             "Paraguay",
	Peru:                 "Peru",
	Philippines:          "Philippines",
	Poland:               "Poland",
	Portugal:             "Portugal",
	Puertorico:           "Puertorico",
	Romania:              "Romania",
	Russia:               "Russia",
	Rwanda:               "Rwanda",
	Samoa:                "Samoa",
	SanMarino:            "SanMarino",
	Saudiarabia:          "Saudiarabia",
	Senegal:              "Senegal",
	Serbia:               "Serbia",
	Singapore:            "Singapore",
	Slovakia:             "Slovakia",
	Slovenia:             "Slovenia",
	SolomonIslands:       "Solomon Islands",
	Somalia:              "Somalia",
	SouthAfrica:          "South Africa",
	SouthKorea:           "South Korea",
	Spain:                "Spain",
	SriLanka:             "Sri Lanka",
	Sudan:                "Sudan",
	Sweden:               "Sweden",
	Switzerland:          "Switzerland",
	Syria:                "Syria",
	Taiwan:               "Taiwan",
	Tajikistan:           "Tajikistan",
	Tanzania:             "Tanzania",
	Thailand:             "Thailand",
	Tonga:                "Tonga",
	Tunisia:              "Tunisia",
	Turkey:               "Turkey",
	Turkmenistan:         "Turkmenistan",
	Uganda:               "Uganda",
	Ukraine:              "Ukraine",
	UnitedArabemirates:   "United Arabemirates",
	UnitedKingdom:        "United Kingdom",
	UnitedStates:         "United States",
	Uruguay:              "Uruguay",
	Uzbekistan:           "Uzbekistan",
	Venezuela:            "Venezuela",
	Vietnam:              "Vietnam",
	Yemen:                "Yemen",
	Zambia:               "Zambia",
	Zimbabwe:             "Zimbabwe",
}

var CountryValidator = validator.NewEnmusFromMap(
	VAL_TAG_COUNTRY, Country, "key",
)

var Language = map[string]string{
	Afrikaans:      "Afrikaans",
	Albanian:       "Albanian",
	Amharic:        "Amharic",
	Arabic:         "Arabic",
	Assamese:       "Assamese",
	Azerbaijani:    "Azerbaijani",
	Belarusian:     "Belarusian",
	Bengali:        "Bengali",
	Bosnian:        "Bosnian",
	Bulgarian:      "Bulgarian",
	Burmese:        "Burmese",
	Catalan:        "Catalan",
	CentralKurdish: "CentralKurdish",
	Chinese:        "Chinese",
	Croatian:       "Croatian",
	Czech:          "Czech",
	Danish:         "Danish",
	Dutch:          "Dutch",
	English:        "English",
	Estonian:       "Estonian",
	Filipino:       "Filipino",
	Finnish:        "Finnish",
	French:         "French",
	Georgian:       "Georgian",
	German:         "German",
	Greek:          "Greek",
	Gujarati:       "Gujarati",
	Hebrew:         "Hebrew",
	Hindi:          "Hindi",
	Hungarian:      "Hungarian",
	Icelandic:      "Icelandic",
	Indonesian:     "Indonesian",
	Italian:        "Italian",
	Japanese:       "Japanese",
	Khmer:          "Khmer",
	Kinyarwanda:    "Kinyarwanda",
	Korean:         "Korean",
	Latvian:        "Latvian",
	Lithuanian:     "Lithuanian",
	Luxembourgish:  "Luxembourgish",
	Macedonian:     "Macedonian",
	Malay:          "Malay",
	Malayalam:      "Malayalam",
	Maltese:        "Maltese",
	Maori:          "Maori",
	Marathi:        "Marathi",
	Mongolian:      "Mongolian",
	Nepali:         "Nepali",
	Norwegian:      "Norwegian",
	Oriya:          "Oriya",
	Pashto:         "Pashto",
	Persian:        "Persian",
	Polish:         "Polish",
	Portuguese:     "Portuguese",
	Punjabi:        "Punjabi",
	Romanian:       "Romanian",
	Russian:        "Russian",
	Samoan:         "Samoan",
	Serbian:        "Serbian",
	Shona:          "Shona",
	Sinhala:        "Sinhala",
	Slovak:         "Slovak",
	Slovenian:      "Slovenian",
	Somali:         "Somali",
	Spanish:        "Spanish",
	Swahili:        "Swahili",
	Swedish:        "Swedish",
	Tajik:          "Tajik",
	Tamil:          "Tamil",
	Telugu:         "Telugu",
	Thai:           "Thai",
	Turkish:        "Turkish",
	Turkmen:        "Turkmen",
	Ukrainian:      "Ukrainian",
	Urdu:           "Urdu",
	Uzbek:          "Uzbek",
	Vietnamese:     "Vietnamese",
}

var LanguageValidator = validator.NewEnmusFromMap(
	VAL_TAG_LANGUAGE, Language, "key",
)
